dist: xenial

language: csharp
os:
  - linux
  - osx
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
 - dotnet build OData2PocoLib/OData2Poco.csproj -f netstandard2.0 -c Release
 - dotnet build OData2Poco.dotnet.o2pgen/OData2Poco.dotnet.o2pgen.csproj -f netcoreapp2.1 -c Release
 - dotnet test OData2Poco.Tests/OData2Poco.Tests.csproj -f netcoreapp2.1 -c Release
 - dotnet test OData2Poco.CommandLine.Test/OData2Poco.CommandLine.Test.csproj -f netcoreapp2.1 -c Release
